version: '3.6'
services: 
    spark-master:
        image: "spark-master" 
        ports : 
            - "8080:8080"
        networks: 
            - "spark-net"
           
    spark-worker1:
        image: "spark-worker"
        ports:
            - "8081:8081"
        container_name: "spark-worker1"
        environment: 
            - CORES=2
            - MEMORY=2G
        networks: 
            - "spark-net"
        depends_on: 
            - "spark-master" 
    
    spark-worker2:
        image: "spark-worker"
        ports:
            - "8082:8081"
        container_name: "spark-worker2"
        environment: 
            - CORES=2
            - MEMORY=2G
        networks: 
            - "spark-net"
        depends_on:
             - "spark-master" 
    
    jupyter-lab:
        image: "jupyterlab"
        ports:
            - "8888:8888"
        container_name: "jupyterlab"
        networks: 
            - "spark-net"
        
networks: 
    spark-net:
        driver: bridge